<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PROMICE</title>
    <link rel="stylesheet" href="./style.css">
</head>

<body>
    <h1>PROMICE</h1>
    <h3>1.Write one example explaining how you can write a callback function.</h3>
    <h4>Ans.</h4>
    <pre>
        ```javascript
function add(a, b, callback) {
  const result = a + b;
  callback(result);
}
function printResult(result) {
  console.log(`The result is ${result}.`);
}
add(2, 3, printResult);
// Output: The result is 5.
```
    </pre>
    <h4>Explanation:
        (1)The `add` function takes two numbers and a callback function as arguments. It adds the two numbers together
        and assigns the result to the `result` variable.
        (2)It then invokes the callback function and passes the `result` as an argument to it.
        (3)The `printResult` function is the callback function passed as an argument to `add`. It takes the `result` as
        an argument and logs it to the console with a message.
        (4) When we call `add(2, 3, printResult)`, it adds 2 and 3 together, which results in 5. It then invokes the
        `printResult` function and passes the result, which logs the message "The result is 5." to the console.
    </h4>
    <br>
    <h3>2.Write a callback function to print numbers from 1 to 7, in which 1 should be printed after 1 sec, 2 should be
        printed after 2 sec, 3 should be printed after 3 sec, and so on. </h3>
    <pre>
        Explain callback hell.
        Numbers
        1
        2
        3
        4
        5
        6
        7
    </pre>
    <h4>Ans.</h4>
    <pre>
        ```javascript
function printNumbersWithDelay() {
  let number = 1;
  function printNumber() {
    console.log(number);
    number++;
    if (number <= 7) {
      setTimeout(printNumber, number * 1000);
    }
  }
  setTimeout(printNumber, 1000);
}
printNumbersWithDelay();
```
Output:
```
1
2
3
4
5
6
7
```
    </pre>
    <h4>Ans.</h4>
    <h4>Explanation:
        (1) The `printNumbersWithDelay` function initializes a variable `number` to 1 and defines a nested function
        `printNumber`.
        (2) The `printNumber` function first logs the value of `number` to the console, increments it by 1, and checks
        if the value of `number` is less than or equal to 7.
        (3) If `number` is less than or equal to 7, it schedules the `printNumber` function to be called after a delay
        equal to `number * 1000` milliseconds, where `number` is the current value of the `number` variable.
        (4) The `setTimeout` method is used to schedule the `printNumber` function to be called after a specified delay.
        (5) Finally, the `printNumbersWithDelay` function calls the `printNumber` function after a delay of 1 second
        using `setTimeout`.
        (6)This creates a chain of callbacks that execute in sequence with increasing delays, resulting in the desired
        output.
        Callback hell is a term used to describe the situation where multiple nested callbacks are used in a program,
        making the code difficult to read and maintain. It arises when a function requires the result of another
        function that is itself asynchronous, and this pattern is repeated multiple times. As a result, the code becomes
        deeply nested, making it hard to follow the program flow. The above example doesn't have any callback hell, but
        a more complex code can have it. To avoid callback hell, developers can use Promises, async/await functions, or
        libraries such as async.js and bluebird.
    </h4>
    <br>
    <h3>3."Write the promise function to print numbers from 1 to 7, in which 1 should be printed after 1 sec, 2 should
        be printed after 2 sec, 3 should be printed after 3 sec, and so on. </h3>
    <pre>
        Numbers
        1
        2
        3
        4
        5
        6
        7"
     </pre>
    <h4>Ans.</h4>
    <pre>
        ```javascript
function printNumberWithDelay(number, delay) {
  return new Promise((resolve) => {
    setTimeout(() => {
      console.log(number);
      resolve();
    }, delay);
  });
}
function printNumbers() {
  let promise = Promise.resolve();
  for (let i = 1; i <= 7; i++) {
    promise = promise.then(() => printNumberWithDelay(i, i * 1000));
  }
}
printNumbers();
```
Output:
```
1
2
3
4
5
6
7
```
    </pre>
    <h4>
        Explanation:
        The `printNumberWithDelay` function takes a `number` and a `delay` as arguments and returns a new Promise.
        (1) Inside the Promise constructor, the `setTimeout` function is used to print the `number` to the console after
        the specified `delay`, and then the `resolve` function is called to fulfill the Promise.
        (2) The `printNumbers` function initializes a `promise` variable to a resolved Promise and then creates a loop
        to print the numbers 1 to 7 with increasing delays.
        (3) Inside the loop, the `promise` variable is updated to a new Promise that is returned by the
        `printNumberWithDelay` function with the current `i` value and a delay equal to `i * 1000` milliseconds.
        (4) This creates a chain of Promises that are executed sequentially, with each Promise waiting for the previous
        Promise to be fulfilled before executing.
        (5)Finally, the `printNumbers` function is called to start the execution of the Promise chain.
        Using Promises allows us to avoid the nested callback structure that can lead to callback hell, making our code
        more readable and maintainable.
    </h4>
    <br>
    <h3>4."Create a promise function accepting an argument, if yes is passed to the function then it should go to
        resolved state and print Promise Resolved, and if nothing is passed
        then it should go to reject the state and catch the error and print Promise Rejected "</h3>
    <h4>Ans.</h4>
    <pre>
    ```javascript
function checkArgument(arg) {
  return new Promise((resolve, reject) => {
    if (arg === "yes") {
      resolve("Promise Resolved");
    } else {
      reject("Promise Rejected");
    }
  });
}
```
Here's how you can use this function:
```javascript
checkArgument("yes")
  .then((result) => console.log(result))
  .catch((error) => console.log(error));
checkArgument()
  .then((result) => console.log(result))
  .catch((error) => console.log(error));
```
Output:
```
Promise Resolved
Promise Rejected
```
</pre>
    <h4>
        Explanation:
        (1) The `checkArgument` function takes an `arg` as an argument and returns a new Promise.
        (2) Inside the Promise constructor, an `if` statement is used to check if the `arg` is equal to `"yes"`.
        (3) If `arg` is equal to `"yes"`, the `resolve` function is called with the message `"Promise Resolved"`.
        (4) Otherwise, the `reject` function is called with the message `"Promise Rejected"`.
        (5) The `then` method is used to handle the fulfilled state of the Promise, which is called when the Promise is
        resolved. It takes a callback function that is passed the resolved value of the Promise as an argument.
        (5) The `catch` method is used to handle the rejected state of the Promise, which is called when the Promise is
        rejected. It takes a callback function that is passed the rejected value of the Promise as an argument.
        In the example above, we call the `checkArgument` function twice with different arguments. The first call passes
        `"yes"`, which resolves the Promise with the message `"Promise Resolved"`. The second call doesn't pass any
        argument, which rejects the Promise with the message `"Promise Rejected"`. We handle both the fulfilled and
        rejected states of the Promise using the `then` and `catch` methods.
    </h4>
    <br>
    <h3>5.Create examples to explain callback function</h3>
    <h4>Ans.</h4>
    <pre>
    ```javascript
function multiplyBy(factor) {
  return (number) => {
    return number * factor;
  };
}
const double = multiplyBy(2);
const triple = multiplyBy(3);
console.log(double(5)); // Output: 10
console.log(triple(5)); // Output: 15
```
</pre>
    <h4>
        (1) The `multiplyBy` function returns a new function that takes a `number` as an argument and multiplies it by
        the `factor` passed to `multiplyBy`.
        (2)This is an example of a higher-order function that returns a function as its result.
        (3) In this example, we create two new functions, `double` and `triple`, by calling `multiplyBy` with `2` and
        `3` as arguments.
        (4) We can then call the `double` and `triple` functions with a number to get the result of multiplying that
        number by 2 or 3, respectively.
        In both examples, the callback function is used to execute code either after an asynchronous operation completes
        or to implement a higher-order function that returns a function as its result.
    </h4>
    <br>
    <h3>6.Create examples to explain callback hell function</h3>
    <h4>Ans.</h4>
    <pre>
    ```javascript
fs.readFile('file1.txt', (err, data) => {
  if (err) {
    console.error(err);
    return;
  }
  fs.readFile('file2.txt', (err, data2) => {
    if (err) {
      console.error(err);
      return;
    }
    fs.readFile('file3.txt', (err, data3) => {
      if (err) {
        console.error(err);
        return;
      }
      // Do something with data from all three files
      console.log(data.toString() + data2.toString() + data3.toString());
    });
  });
});
```

</pre>
    <h4>
        Explanation:
        (1) This is an example of callback hell, which occurs when we have multiple nested callback functions that
        depend on each other to execute.
        (2) In this example, we use the `fs` module in Node.js to read the contents of three different files
        (`file1.txt`, `file2.txt`, and `file3.txt`).
        (3) The first `fs.readFile` function reads the contents of `file1.txt` and passes them to a callback function
        that handles any errors and then reads the contents of `file2.txt` using another `fs.readFile` function.
        (4) The second `fs.readFile` function reads the contents of `file2.txt` and passes them to a callback function
        that handles any errors and then reads the contents of `file3.txt` using yet another `fs.readFile` function.
        (5)The third `fs.readFile` function reads the contents of `file3.txt` and passes them to a callback function
        that handles any errors and then finally logs the combined contents of all three files to the console.
        (6) This code is difficult to read and understand because it contains multiple nested callback functions, which
        can make it hard to follow the flow of the code and debug any errors that occur.
        (7) This problem is commonly known as callback hell or the pyramid of doom. To avoid it, we can use promises or
        async/await functions, which allow us to write asynchronous code in a more readable and maintainable way.
    </h4>
    <br>
    <h3>7.Create examples to explain promises function</h3>
    <h4>Ans.</h4>
    <pre>
    const promise = new Promise((resolve, reject) => { setTimeout(() => { resolve('Hello, World!'); }, 2000); }); promise.then((result) => { console.log(result); })
    .catch((error) => { console.error(error); }); 
</pre>
    <h4>
        (1)This code creates a new promise that resolves after two seconds with the message "Hello, World!"
        (2)We then use the then method to handle the resolved value and log it to the console.
        (3)If an error occurs, we use the catch method to handle it and log it to the console.
    </h4>
    <br>
    <h3>8.Create examples to explain async await function</h3>
    <h4>Ans.</h4>
    <pre>
    const getData = async () => { try { const response = await fetch('https://jsonplaceholder.typicode.com/todos/1'); const data = await response.json(); console.log(data); } 
    catch (error) { console.error(error); } }; getData(); 
</pre>
    <h4>
        (1)This code defines an async function getData that uses the await keyword to wait for the response from a fetch
        request to the JSONPlaceholder API.
        (2)We then use the json method to extract the data from the response, and log it to the console.
        (3)If an error occurs, we use a try/catch block to handle it and log it to the console.
    </h4>
    <h3>9.Create examples to explain promise.all function</h3>
    <h4>Ans.</h4>
    <h4>
        Promise.all() is a method in JavaScript that takes an iterable of promises as an input, and returns a new
        promise that resolves when all of the input promises have resolved, or rejects when any one of the input
        promises rejects. Here are a few examples to explain how to use Promise.all():
        Basic Promise.all() Example
    </h4>
    <pre>
    javascript

    const promise1 = Promise.resolve(1); const promise2 = Promise.resolve(2); const promise3 = Promise.resolve(3);
     Promise.all([promise1, promise2, promise3]) .then((values) => { console.log(values); }) .catch((error) => { console.error(error); }); 
</pre>
    <h4>
        (1)This code creates three promises that immediately resolve with the values 1, 2, and 3.
        (2)We then use Promise.all() to pass an array of these promises as input, and use .then() to log the resolved
        values to the console.
        (3)If an error occurs, we use .catch() to handle it and log it to the console.
    </h4>


</body>

</html>